### ISSUE TITLE
Crash while saving

### ISSUE THREAD

**Issue by jacob1** [flathub/uk.co.powdertoy.tpt#14]
Hi, I'm an upstream developer for The Powder Toy, and we keep getting reports about crashes in unofficial builds of 97.0.
Upstream report: https://github.com/The-Powder-Toy/The-Powder-Toy/issues/911

Reproducing the crash is simple, simply save an offline or online save and the game will crash
![image](https://user-images.githubusercontent.com/1139178/223199143-a6396b29-57c6-4f10-b127-27fb12e3eb21.png)

The fix is to include this commit in your build:
https://github.com/The-Powder-Toy/The-Powder-Toy/commit/853c47b0bda7c757fc54cc11ccf5f32fac02ea6b

This crash does not happen in official 97.0 builds

**Comment by pio2398** [comment]
Thank you for information. I am going to check that tomorrow. Maybe I just used wrong commit in build file.

**Comment by jacob1** [comment]
It is probably correct already. We made this fix after the 97.0 release.

You can find a little more info in the commit message. Our array usage is considered as UB by some newer compilers, and now throws an exception. The compilers we use on the official version don't have this issue.
Since the flatpak build uses one of the problematic compilers, you will have to get the fix in there.

**Comment by pio2398** [comment]
I updated source to last snapshot version.
I am not sure if this is the best solution but adding this commit as a patch seemed worse.
