### ISSUE TITLE
Update to v98

### ISSUE THREAD

**Issue by LegitGreenBoi** [flathub/uk.co.powdertoy.tpt#17]
This flatpak seems to be pretty far out of date. Version 98 just came out a couple days ago, so it would be a good time to get it back up to date.

https://github.com/The-Powder-Toy/The-Powder-Toy/releases

**Comment by pio2398** [comment]
New version came out 3 days ago so I wouldn't call it pretty far out of date. 
Anyway, updated to v98 merged with hacks for appstream validation. I try send patches upstream.
